'\" t
.\"     Title: yubioath\e-cli
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/02/2015
.\"    Manual: Yubico Authenticator Manual
.\"    Source: yubioath-cli
.\"  Language: English
.\"
.TH "YUBIOATH\E\-CLI" "1" "07/02/2015" "yubioath\-cli" "Yubico Authenticator Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yubioath-cli \- Yubico Authenticator command line interface
.SH "SYNOPSIS"
.sp
\fByubioath\-cli\fR [\-h] \fIcommand\fR
.SH "DESCRIPTION"
.sp
The Yubico Authenticator is a graphical desktop tool for generating Open AuTHentication (OATH) event\-based HOTP and time\-based TOTP one\-time password codes, with the help of a YubiKey that protects the shared secrets\&.
.SH "OPTIONS"
.sp
yubioath\-cli has the following options:
.PP
\fB\-h, \-\-help\fR
.RS 4
Shows a list of available sub commands and arguments\&.
.RE
.PP
\fB\-R, \-\-remember\fR
.RS 4
Save any password given for a YubiKey to avoid having to enter it in again\&.
.RE
.PP
\fB\-r, \-\-reader READER\fR
.RS 4
Name to match smartcard reader against (case insensitive)\&.
.RE
.SH "COMMANDS"
.sp
yubioath\-cli supports multiple commands, each with its own options, in addition to the global options:
.SS "yubioath\-cli show [OPTIONS] [QUERY]"
.sp
.if n \{\
.RS 4
.\}
.nf
Display one or more one time codes calculated by the YubiKey\&.
.fi
.if n \{\
.RE
.\}
.PP
\fB\-s1, \-\-slot1 DIGITS\fR
.RS 4
Calculate and show a one time code from slot 1, displaying DIGITS number of digits\&.
.RE
.PP
\fB\-s2, \-\-slot2 DIGITS\fR
.RS 4
Calculate and show a one time code from slot 2, displaying DIGITS number of digits\&.
.RE
.PP
\fB\-t, \-\-timestamp TIMESTAMP\fR
.RS 4
Use the user provided TIMESTAMP instead of the system clock\&.
.RE
.PP
\fBQUERY\fR
.RS 4
A filter string to match credential names agains\&. If given, only credentials containing the QUERY substring will be displayed\&. For HOTP credentials, codes will only be calculated when given a QUERY which uniquely specifices the credential as to avoid unwanted counter incrementation\&.
.RE
.SS "yubioath\-cli put [OPTIONS] KEY"
.sp
.if n \{\
.RS 4
.\}
.nf
Load and store a credential into the YubiKey\&.
.fi
.if n \{\
.RE
.\}
.PP
\fB\-S, \-\-destination DEST\fR
.RS 4
Where DEST is one of:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
the main applet (default)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
the YubiKey standard slot 1\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
the YubiKey standard slot 2\&.
.RE
.RE
.PP
\fB\-N, \-\-name NAME\fR
.RS 4
The name to give the credential\&. When giving a name with an issuer, the issuer and name should be separated by a colon:
\fIissuer:name\fR\&. Not applicable to slot\-based credentials\&.
.RE
.PP
\fB\-A, \-\-oath\-type ALGORITHM\fR
.RS 4
OATH algorithm to use\&. Should be one of
\fBtotp\fR
(default) and
\fBhotp\fR\&. Not applicable to slot\-based credentials\&.
.RE
.PP
\fB\-D, \-\-digits DIGITS\fR
.RS 4
The number of digits to output when generating codes\&. Should be
\fB6\fR
or
\fB8\fR\&. Not applicable to slot\-based credentials\&.
.RE
.PP
\fB\-I IMF, \-\-imf IMF\fR
.RS 4
The initial value to store for the counter\&. Only applicable for HOTP credential\&. Not applicable to slot\-based credentials\&.
.RE
.PP
\fB\-T, \-\-touch\fR
.RS 4
When set, the slot will require the user to press the button on the YubiKey before calculating a code\&.
\fBOnly\fR
applicable to slot\-based credentials\&.
.RE
.PP
\fBKEY\fR
.RS 4
Either a base32 encoded key to use as the secret for the credential, or an otpauth:// URI containing the parameters of the credential\&. When a URI is given the other options are not needed, but can be used to override parameters in the URI, if needed\&.
.RE
.SS "yubioath\-cli delete NAME"
.sp
.if n \{\
.RS 4
.\}
.nf
Deletes a credential from the main OATH credential storage\&.
.fi
.if n \{\
.RE
.\}
.PP
\fBNAME\fR
.RS 4
A filter string that uniquely identifies the credential to delete\&.
.RE
.SS "yubioath\-cli password [OPTIONS]"
.sp
.if n \{\
.RS 4
.\}
.nf
Manage the access password of the OATH applet\&.
.fi
.if n \{\
.RE
.\}
.PP
\fB\-S, \-\-set\fR
.RS 4
Sets a new password for the YubiKey\&.
.RE
.PP
\fB\-U, \-\-unset\fR
.RS 4
Unsets the current password, so that the YubiKey does not require a password to be used\&.
.RE
.PP
\fB\-F, \-\-forget\fR
.RS 4
Remove all access keys stored on disk\&.
.RE
.PP
\fB\-P, \-\-password PASSWORD\fR
.RS 4
Provide the new password for use with
\fB\-\-set\fR
as an argument\&. If not given, the command will prompt the user to enter a new password while masking input\&.
.RE
.SS "yubioath\-cli reset [OPTIONS]"
.sp
.if n \{\
.RS 4
.\}
.nf
Factory\-reset the OATH applet, unsetting any access password and erasing
all stored credentials\&.
.fi
.if n \{\
.RE
.\}
.PP
\fB\-f, \-\-force\fR
.RS 4
Do not prompt for confirmation before resetting\&.
.RE
.SH "BUGS"
.sp
Report bugs in the issue tracker (https://github\&.com/Yubico/yubioath\-desktop/issues)
.SH "SEE ALSO"
.sp
\fByubioath\fR(1)
